version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:14.8.4-ee.0'
    restart: always
    hostname: ${DOMAIN}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN}'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - gitlab_config:/etc/config
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
