version: "3"

services:
  db:
    container_name: glimps_db
    image: postgres:12
    environment:
      POSTGRES_DB: glimps
    volumes:
      - glimps_pgdata:/var/lib/postgresql/data

volumes:
  glimps_pgdata: